apiVersion: apps/v1
kind: Deployment
metadata:
  name: truyumconfig-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Truyumconfig
  template:
    metadata:
      labels:
        app: Truyumconfig
    spec:
      containers:
      - name: truyumrepos
        image: 848954truyumcr.azurecr.io/truyumrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: truyumconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Truyumconfig
